### ISSUE TITLE
Wine 9.5 breaks yabridge

### ISSUE THREAD

**Issue by Yamaha3001** [robbert-vdh/yabridge#322] opened 2024-03-25 21:17 UTC
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I wanted to use Slammer with Bitwig Studio 5.1.6.
The location is set to $HOME/.vst/yabridge and $HOME/.vst3/yabridge. After not finding any plugins I decided to install ardour and just try if its the new Bitwig version, but Ardour tells me he couldn't find libyabridge-vst2.so

Slammer is the first and only plugin tested so far, but if libyabridge-vst2.so is not found, there is no need to try another one, right?

### Operating system

Fedora 39

### How did you install yabridge?

with COPR as described in the README

### yabridge version

5.1

### yabridgectl version

couldnt find that, but i suppose too 5.1

### Wine version

winehq-staging-1:9.5-1.1.x86_64

### Plugin

Slammer

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 5.1.6

### Desktop environment or WM

KDE Plasma 5.27.11

### GPU model

AMD RX 5700XT

### GPU drivers and kernel

amdgpu Kernel 6.7.9-200.fc39

**Comment by robbert-vdh** [comment] 2024-03-25 21:32
Did you install Bitwig and Ardour through Flatpak? If so, try installing them normally, without Flatpak. You'll also want to try an older version of Wine because Wine 9.5 broke compatibility with yabridge. See #320 for that one.

**Comment by Yamaha3001** [comment] 2024-03-26 14:32
how would I install it normally?
There is no rpm file, I could try nix-env, but I think thats not what you meant
Wine 9.1 doesnt solves the issue
Ardour is replying about an NIX_PROFILES environment variable is not set.
First I installed yabridge with nix-env, but after all the errors I deleted the whole /nix directory and installed it the "common" way for fedora.
I tried installing Bitwig on another way with this script https://github.com/varcharfoobar/bitwig-fedora but 1. it downloaded 3.2 or something and 2. it didnt worked either

**Comment by robbert-vdh** [comment] 2024-03-26 18:23
Install yabridge the normal way (don't use Nix), and use one of the various ways people on Fedora use to install Bitwig (unpacking the RPM manually, some conversion tool, etc.). You'll get plenty of hits of you search for that on Google.

**Comment by RustoMCSpit** [comment] 2024-03-26 21:27
i confirm this, Bitwig Studio 5.1.6 breaks yabridge. it was working before i updated and broke immediately upon update. make a new issue name for this

**Comment by RustoMCSpit** [comment] 2024-03-26 21:27
@Yamaha3001 please download an older bitwig package and see if that works

**Comment by robbert-vdh** [comment] 2024-03-26 22:05
> i confirm this, Bitwig Studio 5.1.6 breaks yabridge. it was working before i updated and broke immediately upon update. make a new issue name for this

Bitwig 5.1.6 doesn't break yabridge. Or at least, it doesn't on my machine and I have not heard any reports from others that it does. The problem from this issue is the use of Flatpak, which is not going to work with yabridge.

**Comment by RustoMCSpit** [comment] 2024-03-26 22:11
> > i confirm this, Bitwig Studio 5.1.6 breaks yabridge. it was working before i updated and broke immediately upon update. make a new issue name for this
> 
> Bitwig 5.1.6 doesn't break yabridge. Or at least, it doesn't on my machine and I have not heard any reports from others that it does. The problem from this issue is the use of Flatpak, which is not going to work with yabridge.

i just used timeshift to go back to an older bitwig (both not flatpak) and it works again. 5.1.6 breaks yabridge

**Comment by robbert-vdh** [comment] 2024-03-26 22:12
It does not. You likely also updated Wine to 9.5 when you updated Bitwig.

**Comment by RustoMCSpit** [comment] 2024-03-27 00:49
> It does not. You likely also updated Wine to 9.5 when you updated Bitwig.

youre right, just re-tested this. older bitwig breaks with new wine. when can this be fixed?

**Comment by RustoMCSpit** [comment] 2024-03-27 01:24
@Yamaha3001 rename issue 'Wine 9.5 breaks yabridge"

**Comment by robbert-vdh** [comment] 2024-03-28 17:54
Closing as a duplicate of #320.

> > It does not. You likely also updated Wine to 9.5 when you updated Bitwig.
> 
> youre right, just re-tested this. older bitwig breaks with new wine. when can this be fixed?

When someone working on Wine fixes it. There have not yet been any replies on the bug report. I'd fix it myself, but I don't know the context for the original change and I also haven't gotten a response on IRC yet when I asked about it. So it could take a while, until a Wine contributor notices the issue.

**Closed** 2024-03-28 17:55 UTC

**Comment by RustoMCSpit** [comment] 2024-03-28 18:13
no reason to close this, just put it under a needs help tag

**Comment by robbert-vdh** [comment] 2024-03-28 18:51
They're the same issue. Having duplicates of the same issue open only makes things more confusing by spreading out the conversation.
