### ISSUE TITLE
Cursor misaligned when window is moved in Tracktion Waveform

### ISSUE THREAD

**Issue by russinet** [robbert-vdh/yabridge#378] opened 2024-11-03 05:32 UTC
### Thanks for giving yabridge a shot!

- [x] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

In Tracktion Waveform 13, if I try to drag a plugin window, the cursor input gets messed up. It seems that the window offset is not being taken into account when calculating where the cursor should be. A fix that I found is opening up the little menu at the top of the window, which seems to reset it back to the right point. However, this is extremely annoying, especially if I have a lot of plugins that I need to move around. This issue occurs with every plugin I tried (Arturia, Spitfire, and Beatskillz). However, native plugins work just fine which leads me to believe that this is a compatability issue with Yabridge / Wine. 

### What did you expect to happen?

The buttons / knobs under the cursor should be selected even if the window is moved.

### What actually happened?

There appears to be an offset, as if the change in window position is not being taken into account unless I do the dropdown menu thing. Please see the video for a visual demonstration

https://github.com/user-attachments/assets/7814392a-22f4-4215-ae62-8e07b7157c33

### Operating system

Arch Linux

### How did you install yabridge?

AUR Package

### yabridge version

5.1.0

### yabridgectl version

5.1.0

### Wine version

wine-9.20 (Staging)

### Plugin

All Plugins

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

Tracktion Waveform Free 13

### Desktop environment or WM

KDE Plasma 6.2.1 on Wayland

### GPU model

RTX 3080 Laptop GPU (May be using Intel integrated graphics TigerLake-H GT1)

### GPU drivers and kernel

i915 for integrated, nvidia (proprietary) for dedicated

### Debug log

Unable to obtain logs, Waveform hangs whenever trying to open a plugin when the command from the second step is used.

### Anything else?

Any help would be extremely appreciated! This is driving me nuts and I don't want to learn another DAW.

**Comment by Seliaste** [comment] 2024-11-30 22:51
Same issue here on a spire, arturia piano v2 and valhalla supermassive all in vst3.

**Comment by bertin0** [comment] 2024-12-09 18:56
I have a similar issue with pianoteq in Ardour, the cursor seems to be sent at the absolute screen position not relative to the actual window position. can provide further logs if needed. also on Arch and Gnome wayland

**Comment by giantg** [comment] 2024-12-23 04:14
Hi All,

Joining in on the fun and hopefully helping:  I ran into similar problems with the Korg M1 VST (version 1.71):

![image](https://github.com/user-attachments/assets/96d43ee4-4010-497c-82a5-4e0e7d1b4cd0)

@russinet you were spot on!  It is taking the coordinates from the top left of the screen (vs. the top left of the window).  I would have never thought to try / check that, but moving the window as close to the top left reduced the offset amount for me as well.  Thank you for that!

I to am running arch and decided to try cloning the official Arch Wine package source from git:
https://gitlab.archlinux.org/archlinux/packaging/packages/wine

I then reverted back to the 9.19-1 revision of the package (so Wine version 9.19) and did a ```makepkg -s```

After installing my manually downgraded Wine version 9.19 I can confirm that the plugin now behaves and the mouse coordinates match the mouse cursor in the Korg M1 VST (via ya-bridge).  This does appear to be a incompatibility introduced via Wine.  I haven't had a chance to build Wine 9.20, or 9.21 yet to try and locate which exact version of Wine caused the issue (I'll report back when I'm able to build those and confirm.)

Oh, and here's my info:



### Operating system

Arch Linux
### How did you install yabridge?

AUR Package
### yabridge version

5.1.1
### yabridgectl version

5.1.1
### Wine version

wine-9.19
### Plugin

Korg M1 VST (version 1.71)
### Plugin type

VST2
### Plugin architecture

64-bit
### Host

Reaper v7.28 rev 32cb21 (linux-x86_64)
### Desktop environment or WM
GNOME 47.2 on Wayland

### GPU model

RTX 4060 Laptop GPU (Acer Predator Helios NEO 16)
### GPU drivers and kernel

i915 for integrated, nvidia (proprietary) for dedicated

**Comment by giantg** [comment] 2024-12-23 04:51
Ok, I can confirm that it seems to be the current Wine 9.22 version that introduces this issue.

I manually build 9.19, 9.20, 9.21, and 9.22 and version 9.22 (whether manually built by myself or installed from the official Arch package) introduces the cursor offset.

I was curious and looked at the Official Wine Source asking git for a comparison, but the changes are vast and more than I could look through at this sleepy hour.  I hope these comments help and as always a HUGE THANK YOU to the whole yabridge project and to you @russinet for opening this issue!

**Comment by muxosu** [comment] 2024-12-23 22:18
Can also confirm, that the issue, where the pointer is aligned to the top left, occurs only since wine 9.22 for me.
Tested in wine 9.20 and wine 9.21, on both versions of the package it works fine.

**Operating system**

Arch Linux

**How did you install yabridge?**

AUR Package

**yabridge version**

5.1.1

**yabridgectl version**

5.1.1

**Wine version**

wine-9.21

**Plugin**

all windows plugins

**Plugin type**

VST2 & VST3

**Plugin architecture**

64-bit

**Host**

Renoise 64Bit - V3.4.4 

**Desktop environment or WM**

KDE Plasma 6.2.4 on Wayland

**GPU model**

NVIDIA GTX1060 6GB

**GPU drivers and kernel**

NVIDIA 565.77 (proprietary)

**Comment by asymcon** [comment] 2024-12-25 20:25
Still a problem in 10.0~rc3, can confirm 9.22 started this issue, 9.21 works fine


Operating system
Lubuntu

How did you install yabridge?
winehq repo

yabridge version
5.1.1

yabridgectl version
5.1.1

Wine version
10.0~rc3~noble-1

Plugin
Audio Modeling Violin 3

Plugin type
VST3

Plugin architecture
64-bit

Host
Reaper v7.22

Desktop environment or WM
Openbox with LXQT

GPU model
AMD Vega RX 7

GPU drivers and kernel
Proprietary, 6.8.0-51 generic

**Comment by robbert-vdh** [comment] 2024-12-27 15:10
I forgot to mark this issue as a duplicate of #382, sorry for that! Closing this one so there's only one open issue about Wine 9.22's changes.

**Closed by robbert-vdh** 2024-12-27 15:10 UTC
