### ISSUE TITLE
Bitwig 3.3 beta 2 / Deleting plugin instance does not work

### ISSUE THREAD

**Issue by abique** [robbert-vdh/yabridge#45] opened 2020-10-21 19:06 UTC
Hi,

When I delete plugin instance which are bridged using yabridge, Bitwig fails to save the plugin state prior to deleting the plugins and I have left over processes that prevent Bitwig from quitting.

I think there are some FD that we don't mark with cloexec and they are inherited by your software and keeps the pipe/socket open.

I wonder why there are left-over processes? I believe that if the BitwigAudioEngine end is gone, then your wine plugin host has no one to talk to and should quit isn't it?

Steps:
- add Spire
- add Fabfilter Pro-Q3
- add Fabfilter Pro-R
- delete them one by one

Regards,
Alex

**Comment by abique** [comment] 2020-10-21 19:41
I've added some CLOEXEC and it seems to help.
Do you use fork? vfork? clone?

**Comment by robbert-vdh** [comment] 2020-10-21 19:53
Interesting. I tried a few different situations with wine-nspa 5.9, BWS 3.3 beta 1 and [this branch](https://github.com/robbert-vdh/yabridge/tree/removeme/bitwig-3.3-beta-hack) to work around the state loading issues:

- With the 'Within Bitwig', 'Together' and 'By manufacturer' plugin hosting modes and Pro-Q3 hosted within a plugin group, closing Pro-Q3 will cause Pro-R to get stuck during the `effGetProgram()` part of the plugin closing process (meaning that yabridge will have passed the call on to Pro-R, and is stuck waiting for a response)
- With the 'Within Bitwig', 'Together' and 'By manufacturer' plugin hosting modes and Pro-Q3 hosted individually (i.e. without any additional configuration) everything works fine.
- WIth the 'By plug-in' and 'Invididually' plugin hosting modes everything works fine regardless of how Pro-Q3 gets hosted.

Does the issue also happen for you with either of the last two plugin hosting modes? And did you have a [plugin group](https://github.com/robbert-vdh/yabridge#plugin-groups) set up for Pro-Q3? There are a few small differences in how individually hosted plugins and plugin groups spawn and/or connect to a Wine process, but if that's not the case then this must be a separate issue.

**Comment by robbert-vdh** [comment] 2020-10-21 19:56
> I've added some CLOEXEC and it seems to help.
> Do you use fork? vfork? clone?

On the Linux side yabridge only uses `std::thread` and Boost.Process for spawning and managing child processes.

**Comment by abique** [comment] 2020-10-21 19:56
In the plugin host we already had proper CLOEXEC, but in the AudioEngine, two of them were missing.
No I'm not using groups yet.

**Comment by abique** [comment] 2020-10-21 19:57
> > I've added some CLOEXEC and it seems to help.
> > Do you use fork? vfork? clone?
> 
> On the Linux side yabridge only uses `std::thread` and Boost.Process for spawning and managing child processes.

Make sure it uses vfork at least, or clone() with the right flags.

**Comment by abique** [comment] 2020-10-21 19:59
https://man7.org/linux/man-pages/man2/vfork.2.html

**Comment by abique** [comment] 2020-10-21 19:59
https://www.boost.org/doc/libs/1_64_0/doc/html/boost/process/posix/use_vfork.html

**Comment by robbert-vdh** [comment] 2020-10-21 20:41
I sadly can't reproduce the issue with beta 1, but I've changed the Wine process spawning to use `vfork()` in ce385f39d3efcb2e6f67614cb46c2034fe32d575. If you're not building from source then you can grab a compiled version from the [automated builds](https://github.com/robbert-vdh/yabridge/actions/runs/320676297) page if you want to give this a try. During `effClose()` everything should be [cleaned up](https://github.com/robbert-vdh/yabridge/blob/ce385f39d3efcb2e6f67614cb46c2034fe32d575/src/plugin/plugin-bridge.cpp#L465-L472), so I can't think of anything that would cause issues with dangling resources.

If this doesn't change anything, could you try running Bitwig with the command below, go through the steps again until the point where Bitwig can't save plugin state anymore, and then upload `/tmp/yabridge.log` here? Maybe yabridge is doing something strange your system.

```shell
env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=1 bitwig-studio
```

**Closed** 2020-11-06 08:01 UTC
