### ISSUE TITLE
VPS Avenger Crash on load(Bitwig 3.2.8)

### ISSUE THREAD

**Issue by ChrisHaggart** [robbert-vdh/yabridge#39] opened 2020-10-01 22:25 UTC
**Problem description**
When loading VPS Avenger into my DAW, the plugin crashes right before the UI appears.

**What did you expect to happen?**
Load VPS Avenger in bitwig.

**What actually happened?**
The plugin crashes

**System information**
- Operating system: 5.8.6-1-MANJARO 
- Wine version: Wine-5.12
- Installation method: symlinks, yabridgectl
- yabridge version: 1.6.1
- yabridgectl version: 1.6.1

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/5315115/yabridge.log)

**Comment by robbert-vdh** [comment] 2020-10-01 23:08
Hi,

I don't have Avenger installed, but this would be caused by some missing library function. Have you already tried installing the usual suspects like the MSVC++ runtimes? You can install those by running `winetricks vcrun2019` (and `winetricks gdiplus` might also be useful in some cases). If that doesn't fix anything then you can try starting bitwig with `env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2 WINEDEBUG=warn+all bitwig-studio` to hopefully get some more information on what's going wrong.

**Comment by ChrisHaggart** [comment] 2020-10-02 09:06
Hey Robert!

Thanks for the fast reply! I will try the vcrun2019 later today,as gdiplus is already installed for serum which works awesome!
I'll reach back to you with the feedback in any scenario,and try running bitwig with the logging options you have provided!

Thank you in advance!

**Comment by robbert-vdh** [comment] 2020-10-10 14:56
Have you managed to figure this one out yet? I just downloaded the demo for Avenger 1.4.2 from [this page](https://www.vengeance-sound.com/plugins.php?sub=Vengeance%20Producer%20Suite%20Avenger&issue=TRY%20DEMO) and installed it in a clean Wine prefix. Opening the editor GUI does indeed crash the plugin like you described. I spent some time seeing if changing .dll overrides would fix the issue (that's usually the case for misbehaving plugins), but I haven't been able to figure out what's wrong without getting into the really low level nitty gritty. There also don't seem to be any reports of people who did get the plugin working under Wine, so it might just be that they use some functionality that Wine has not yet implemented or has implemented differently from what Avenger expects.

**Comment by ChrisHaggart** [comment] 2020-10-12 21:35
Hey Robert!

Sorry for the late reply, unfortunately, no :/. I have been going up and over this issue, but nothing seems to cut the mustard. I guess I'm just gonna have to embrace the thought of leaving this plugin behind , well sh*t happens :). 

Thanks for the effort though, and keep up the good work with Yabridge !!

**Comment by robbert-vdh** [comment] 2020-10-30 23:47
I'll close this since this is sadly not something we can fix on yabridge's side, but if you do find a way to get the plugin to run (or if it suddenly just starts working), then please let me know!

**Closed by robbert-vdh** 2020-10-30 23:47 UTC
Labels: wine-issue
