### ISSUE TITLE
DSK Saxophones randomly changing sustained notes

### ISSUE THREAD

**Issue by ajkachnic** [robbert-vdh/yabridge#177] opened 2022-05-09 20:38 UTC
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I set up a fresh wine prefix and installed a couple VST instruments. The two that have given me trouble so far are [DSK Saxophone](https://www.dskmusic.com/dsk-saxophones/) and [Keyzone Classic](https://plugins4free.com/plugin/2848/). With either of them, on a long sustained note, they would jump up (seemingly) randomly. Here is an exported audio sample that demonstrates this

https://user-images.githubusercontent.com/44317699/167492238-2df6462b-f04b-4f09-b14e-6b2c0267d5bc.mp4

### What did you expect to happen?

I expected the VST to hold the sustained pitches for their specified length. For example, this is what the other sample *should* sound like (recorded with a linux native VST)

https://user-images.githubusercontent.com/44317699/167494078-9d0ee768-045e-4cb4-a562-30dd8de9c9f1.mp4

### What actually happened?

It randomly shot up to another note. It's fairly inconsistent because sometimes it plays the notes perfectly, but at other times it changes notes.

### Operating system

NixOS

### How did you install yabridge?

From nixpkgs

### yabridge version

3.6.0

### yabridgectl version

3.6.0

### Wine version

Wine Staging 6.22

### Plugin

DSK Saxophone

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Reaper

### Debug log

The log looked pretty uninteresting to me, but here it is: [yabridge.log](https://github.com/robbert-vdh/yabridge/files/8655149/yabridge.log)

### Anything else?

This seems to be a problem with a bunch of different plugins, but I'm not sure what the cause would be

**Comment by robbert-vdh** [comment] 2022-05-09 21:18
I can assure you that's not a problem with yabridge itself. (I also wasn't able to reproduce this with REAPER, that DSK Saxophones plugin, and wine-tkg 7.8-ish)

But since you're using REAPER, have you tried disabling anticipative FX processing? Or have you tried this plugin in, say, Bitwig Studio? I don't know how well made these plugins are, but perhaps they somehow end up using the actual elapsed wall time as part of a calculation somewhere.

Unrelated, but you'll also want to fix your realtime priviliges and memory locking limits (you should normally also be getting a notification about this, but I wouldn't be surprised if notify-send is missing on your system).

**Comment by robbert-vdh** [comment] 2022-06-13 15:28
Closing this since it's not a yabridge issue and there hasn't been a response in over a month.

**Closed by robbert-vdh** 2022-06-13 15:28 UTC
Labels: plugin-bug
