### ISSUE TITLE
yabridge plugins fail to load after update to wine 9.5-9.7

### ISSUE THREAD

**Issue by mrbumpy409** [robbert-vdh/yabridge#320] opened 2024-03-23 17:11 UTC
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

After upgrading from wine-devel 9.4 to version 9.5, trying to use a plugin through yabridge crashes REAPER. Running REAPER from the terminal, I get the following output when it crashes:
```
09:03:23 [sforzando VST_x64-157FRTVl] Initializing yabridge version 5.1.0
09:03:23 [sforzando VST_x64-157FRTVl] library:       '/home/chris/.local/share/yabridge/libyabridge-vst2.so'
09:03:23 [sforzando VST_x64-157FRTVl] host:          '/home/chris/.local/share/yabridge/yabridge-host.exe'
09:03:23 [sforzando VST_x64-157FRTVl] plugin:        '/home/chris/.wine/drive_c/Program Files/Common Files/VST2/Plogue Art et Technologie, Inc/sforzando VST_x64.dll'
09:03:23 [sforzando VST_x64-157FRTVl] plugin type:   'VST2'
09:03:23 [sforzando VST_x64-157FRTVl] realtime:      'yes'
09:03:23 [sforzando VST_x64-157FRTVl] sockets:       '/run/user/1000/yabridge-sforzando VST_x64-157FRTVl'
09:03:23 [sforzando VST_x64-157FRTVl] wine prefix:   '/home/chris/.wine'
09:03:23 [sforzando VST_x64-157FRTVl] wine version:  '9.5'
09:03:23 [sforzando VST_x64-157FRTVl] 
09:03:23 [sforzando VST_x64-157FRTVl] config from:   '/home/chris/.vst/yabridge/yabridge.toml, section "Plogue Art et Technologie, Inc/sforzando VST_x64.so"'
09:03:23 [sforzando VST_x64-157FRTVl] hosting mode:  'plugin group "sforzando", 64-bit'
09:03:23 [sforzando VST_x64-157FRTVl] other options: 'editor: force drag-and-drop', 'frame rate: 24 fps'
09:03:23 [sforzando VST_x64-157FRTVl] 
09:03:23 [sforzando VST_x64-157FRTVl] Enabled features:
09:03:23 [sforzando VST_x64-157FRTVl] - bitbridge support
09:03:23 [sforzando VST_x64-157FRTVl] - CLAP support
09:03:23 [sforzando VST_x64-157FRTVl] - VST3 support
09:03:23 [sforzando VST_x64-157FRTVl] 
09:03:24 [sforzando VST_x64-157FRTVl] [Wine STDERR] 007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
09:03:24 [sforzando VST_x64-157FRTVl] [Wine STDERR] 007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
09:03:24 [sforzando VST_x64-157FRTVl] [Wine STDERR] 007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
09:03:24 [sforzando VST_x64-157FRTVl] [Wine STDERR] 007c:fixme:wineusb:query_id Unhandled ID query type 0x5.
09:03:25 [sforzando VST_x64-157FRTVl] [Wine STDOUT] Application could not be started, or no application associated with the specified file.
09:03:25 [sforzando VST_x64-157FRTVl] [Wine STDOUT] ShellExecuteEx failed: File not found.
09:03:25 [sforzando VST_x64-157FRTVl] [Wine STDOUT]
```
Running yabridge in debug mode doesn't generate any more info than what is above, so I have not included it.

Running `yabridgectl sync` generates the following output:
```
Finished setting up 132 plugins (0 new), skipped 9 non-plugin .dll files

Warning: Could not run 'yabridge-host.exe'. Wine reported the following error:

    <no_output>

    Make sure that you have downloaded the correct version of yabridge for your distro.
    This can also happen when using a version of Wine that's not compatible with this version of yabridge, in which case you'll need to upgrade Wine. Your current Wine version is '9.5'. See the link below for
    instructions on how to upgrade your installation of Wine.

    https://github.com/robbert-vdh/yabridge#troubleshooting-common-issues
```
## Workaround

Downgrading wine-devel packages to version 9.4 solves the issue.

### What did you expect to happen?

The plugin should load and produce audio.

### What actually happened?

REAPER crashes.

### Operating system

KDE neon User Edition 6.0

### How did you install yabridge?

from the releases page

### yabridge version

5.1.0

### yabridgectl version

5.1.0

### Wine version

Wine Development 9.5

### Plugin

any

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

REAPER v7.11

**Comment by saffronmash** [comment] 2024-03-24 04:42
I have had a very similar issue running BitWig 5.1.6 - after running from the terminal and attempting to load a VST or CLAP onto an audio track I get the following:

`[2024-03-24 15:32:26.512 float-document-master info] Starting engine for New 1
[2024-03-24 15:32:26.515 float-gui-widgets info] Connecting audio engine to project New 1
[2024-03-24 15:32:26.516 float-gui-widgets info] New audible project 9
[2024-03-24 15:32:26.531 float-engine-communication info] Engine process successfully started
[2024-03-24 15:32:27.038 package-manager info] Scanning for available packages...
[2024-03-24 15:32:27.053 indexer info] Finished crawling directory /opt/bitwig-studio/Library/devices and found 118 files
[2024-03-24 15:32:27.055 base-util info] Updating index /opt/bitwig-studio/Library/devices for phase devices: time=7.179966
[2024-03-24 15:32:27.056 indexer info] Finished crawling directory /opt/bitwig-studio/Library/modulators and found 43 files
[2024-03-24 15:32:27.057 base-util info] Updating index /opt/bitwig-studio/Library/modulators for phase devices: time=1.363238
[2024-03-24 15:32:27.066 indexer info] Finished crawling directory /opt/bitwig-studio/Library/modules and found 218 files
[2024-03-24 15:32:27.066 base-util info] Updating index /opt/bitwig-studio/Library/modules for phase devices: time=9.46948
[2024-03-24 15:32:27.067 package-manager info] Scanning for available packages...
[2024-03-24 15:32:27.077 indexer info] Finished crawling directory /home/saffronmash/Bitwig Studio/Library and found 0 files
[2024-03-24 15:32:27.077 base-util info] Updating index /home/saffronmash/Bitwig Studio/Library for phase projects: time=10.69201
[2024-03-24 15:32:27.081 indexer info] Finished crawling directory /home/saffronmash/Bitwig Studio/Projects and found 14 files
[2024-03-24 15:32:27.081 base-util info] Updating index /home/saffronmash/Bitwig Studio/Projects for phase projects: time=3.874165
[2024-03-24 15:32:27.092 indexer info] Finished crawling directory /home/saffronmash/Bitwig Studio/Library and found 0 files
[2024-03-24 15:32:27.092 base-util info] Updating index /home/saffronmash/Bitwig Studio/Library for phase samples: time=10.397108
[2024-03-24 15:32:27.120 package-manager info] Finished scanning for available packages
[2024-03-24 15:32:27.155 package-manager info] Finished scanning for available packages
[2024-03-24 15:32:27.182 float-library-master warning] 222 duplicates found in file results
[2024-03-24 15:32:27.191 float-engine-communication info] Engine connecting with sample rate 48000 and block size 1024
[2024-03-24 15:32:27.252 float-library-master warning] 222 duplicates found in file results
[2024-03-24 15:32:27.343 float-document-master info] Engine connected to project New 1
[2024-03-24 15:32:27.365 indexer info] Finished crawling directory /home/saffronmash/.BitwigStudio/installed-packages/5.0 and found 11295 files
[2024-03-24 15:32:27.366 base-util info] Updating index /home/saffronmash/.BitwigStudio/installed-packages/5.0 for phase samples: time=273.58765
[2024-03-24 15:32:27.369 float-document-master info] FloatDocument.isEngineReadyChanged(false->true)
[2024-03-24 15:32:27.604 indexer info] Finished crawling directory /home/saffronmash/.BitwigStudio/installed-packages/5.0 and found 10387 files
[2024-03-24 15:32:27.604 base-util info] Updating index /home/saffronmash/.BitwigStudio/installed-packages/5.0 for phase packages: time=238.0548
[2024-03-24 15:32:27.608 indexer info] Finished crawling directory /home/saffronmash/Bitwig Studio/Library and found 0 files
[2024-03-24 15:32:27.608 base-util info] Updating index /home/saffronmash/Bitwig Studio/Library for phase wavetable: time=4.191079
[2024-03-24 15:32:27.614 indexer info] Finished crawling directory /home/saffronmash/Bitwig Studio/Library and found 0 files
[2024-03-24 15:32:27.614 base-util info] Updating index /home/saffronmash/Bitwig Studio/Library for phase impulse: time=5.773274
[2024-03-24 15:32:27.619 indexer info] Finished crawling directory /home/saffronmash/Bitwig Studio/Library and found 0 files
[2024-03-24 15:32:27.619 base-util info] Updating index /home/saffronmash/Bitwig Studio/Library for phase curve: time=4.543992
[2024-03-24 15:32:27.624 indexer info] Finished crawling directory /home/saffronmash/Bitwig Studio/Library and found 6 files
[2024-03-24 15:32:27.624 base-util info] Updating index /home/saffronmash/Bitwig Studio/Library for phase content: time=5.346802
[2024-03-24 15:32:27.638 indexer info] Could not read metadata for carla.vst/libcarla_host-plugin.so com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
[2024-03-24 15:32:27.639 indexer info] Could not read metadata for carla.vst/libcarla_interposer-x11.so com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
[2024-03-24 15:32:27.643 indexer info] Could not read metadata for carla.vst/libcarla_interposer-jack-x11.so com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
[2024-03-24 15:32:27.644 indexer info] Could not read metadata for carla.vst/styles/carlastyle.so com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
[2024-03-24 15:32:27.644 indexer info] Could not read metadata for carla.vst/libcarla_native-plugin.so com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
[2024-03-24 15:32:27.646 indexer info] Could not read metadata for carla.vst/libcarla_interposer-safe.so com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
[2024-03-24 15:32:27.648 indexer info] Could not read metadata for carla.vst/libcarla_utils.so com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
[2024-03-24 15:32:27.649 indexer info] Could not read metadata for carla.vst/carla-bridge-lv2.so com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
[2024-03-24 15:32:27.658 indexer info] Could not read metadata for dexed-linux64/Dexed.lv2/Dexed.so com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
[2024-03-24 15:32:27.662 indexer info] Finished crawling directory /usr/lib/vst and found 26 files
[2024-03-24 15:32:27.663 base-util info] Updating index /usr/lib/vst for phase content: time=38.786694
[2024-03-24 15:32:27.670 indexer info] Finished crawling directory /usr/lib/vst3 and found 26 files
[2024-03-24 15:32:27.670 base-util info] Updating index /usr/lib/vst3 for phase content: time=6.801905
[2024-03-24 15:32:27.700 indexer info] Finished crawling directory /home/saffronmash/.vst3 and found 122 files
[2024-03-24 15:32:27.701 base-util info] Updating index /home/saffronmash/.vst3 for phase content: time=30.533571
[2024-03-24 15:32:27.701 indexer info] Finished crawling directory /home/saffronmash/.wine/drive_c/Program Files/VSTPlugins and found 0 files
[2024-03-24 15:32:27.701 base-util info] Updating index /home/saffronmash/.wine/drive_c/Program Files/VSTPlugins for phase content: time=0.717487
[2024-03-24 15:32:27.703 indexer info] Finished crawling directory /usr/lib/clap and found 18 files
[2024-03-24 15:32:27.704 base-util info] Updating index /usr/lib/clap for phase content: time=2.21915
[2024-03-24 15:32:27.736 float-library-master warning] 222 duplicates found in file results
[2024-03-24 15:32:27.739 indexer info] Finished crawling directory /home/saffronmash/.vst and found 54 files
[2024-03-24 15:32:27.739 base-util info] Updating index /home/saffronmash/.vst for phase content: time=35.10242
[2024-03-24 15:32:27.739 indexer info] Finished crawling directory /home/saffronmash/.clap and found 1 files
[2024-03-24 15:32:27.740 base-util info] Updating index /home/saffronmash/.clap for phase content: time=0.607909
[2024-03-24 15:32:27.803 indexer info] Finished crawling directory /home/saffronmash/Music/Samples and found 5820 files
[2024-03-24 15:32:27.803 base-util info] Updating index /home/saffronmash/Music/Samples for phase content: time=63.311928
[2024-03-24 15:32:27.807 indexer info] Finished crawling directory /home/saffronmash/Bitwig Studio/Library and found 0 files
[2024-03-24 15:32:27.807 base-util info] Updating index /home/saffronmash/Bitwig Studio/Library for phase plugin_presets: time=4.236335
[2024-03-24 15:32:27.892 float-library-master warning] 222 duplicates found in file results
[2024-03-24 15:32:30.911 float-document-master info] Stopping engine for New 1
[2024-03-24 15:32:30.914 float-gui-widgets info] No current audible project
[2024-03-24 15:32:30.914 float-document-master info] Starting engine for New 2
[2024-03-24 15:32:30.915 float-gui-widgets info] Connecting audio engine to project New 2
[2024-03-24 15:32:30.915 float-gui-widgets info] New audible project 10
[2024-03-24 15:32:31.095 ramona-server error] Connection broken with client:
        java.io.EOFException
        at com.bitwig.ramona.serial.lhL.moS(SourceFile:263)
        at com.bitwig.ramona.serial.lhL.iET(SourceFile:413)
        at cvf.IVN(SourceFile:777)
        at cvf.rIY(SourceFile:599)
        at cvf.rIY(SourceFile:580)
        at com.bitwig.ramona.protocol.fNi.rIY(SourceFile:88)
        at cwb.qlF(SourceFile:393)
        at cwc.run(SourceFile:277)

[2024-03-24 15:32:31.095 float-document-master info] FloatDocument.engineDisconnected()
[2024-03-24 15:32:31.098 float-document-master info] FloatDocument.isEngineReadyChanged(true->false)
[2024-03-24 15:32:31.159 float-engine-communication info] Engine connecting with sample rate 48000 and block size 1024
[2024-03-24 15:32:31.271 float-library-master warning] 222 duplicates found in file results
[2024-03-24 15:32:31.292 float-library-master warning] 222 duplicates found in file results
[2024-03-24 15:32:31.353 float-document-master info] Engine connected to project New 2
[2024-03-24 15:32:31.369 float-document-master info] FloatDocument.isEngineReadyChanged(false->true)
[2024-03-24 15:32:35.931 float-document-master info] FloatDocument.isEngineReadyChanged(true->false)
[2024-03-24 15:32:35.962 float-document-master info] FloatDocument.isEngineReadyChanged(false->true)
[2024-03-24 15:33:03.945 float-document-master info] FloatDocument.isEngineReadyChanged(true->false)
[2024-03-24 15:33:07.370 ramona-server error] Connection broken with client:
        java.io.EOFException
        at com.bitwig.ramona.serial.lhL.moS(SourceFile:263)
        at com.bitwig.ramona.serial.lhL.iET(SourceFile:413)
        at cvf.IVN(SourceFile:777)
        at cvf.rIY(SourceFile:599)
        at cvf.rIY(SourceFile:580)
        at com.bitwig.ramona.protocol.fNi.rIY(SourceFile:88)
        at cwb.qlF(SourceFile:393)
        at cwc.run(SourceFile:277)

[2024-03-24 15:33:07.371 float-document-master error] Error launching or running engine for project New 2: Communications with engine lost
[2024-03-24 15:33:07.372 float-document-master info] FloatDocument.engineDisconnected()
[2024-03-24 15:33:07.376 float-engine-communication error] Error launching or running the engine process: Process exited with an error: 1 (Exit value: 1)
[2024-03-24 15:33:07.377 float-main-app info] Found engine crash report file BITWIG_ENGINE_CRASH.txt.
[2024-03-24 15:33:07.391 ramona-server error] Connection broken with client:
        java.io.EOFException
        at com.bitwig.ramona.serial.lhL.moS(SourceFile:263)
        at com.bitwig.ramona.serial.lhL.iET(SourceFile:413)
        at cvf.IVN(SourceFile:777)
        at cvf.rIY(SourceFile:599)
        at cvf.rIY(SourceFile:580)
        at com.bitwig.ramona.protocol.fNi.rIY(SourceFile:88)
        at cwb.qlF(SourceFile:393)
        at cwc.run(SourceFile:277)
`

**Comment by rolodoom** [comment] 2024-03-24 11:25
Same here. I was in production (using UbuntuStudio 23.10) and yabridge stopped working. So I downgraded to Wine Staging 9.4 and will uphold until any news about the issue.

**Comment by mrbumpy409** [comment] 2024-03-24 13:48
@rolodoom: Just so you know, one of the current wine-staging patches [prevents some VST plugins from working](https://bugs.winehq.org/show_bug.cgi?id=56396), including Plogue sforzando and ARIA Engine. This was broken in wine-staging 9.3, but I'm not sure if it's been fixed yet in 9.4. Anyway, you may wish to downgrade to 9.2 if any of your plugins are affected. Wine-devel is not affected.

**Comment by unholyeyebrows** [comment] 2024-03-24 19:52
Also seeing the same problem on Kubuntu 23.10 / Wine Staging 9.5 (was working prior to today's update). Using Cheery Audio plugins as an example, I can run their stand-alone app via the 'wine directory fine, but when loaded as a VST the same plugin will crash the VST host or plugin sandbox (confirmed with Reaper, Waveform, Studio One, and Bitwig).

**Comment by hyuri** [comment] 2024-03-25 18:48
Same issue here with Wine Staging 9.5.

It was working fine with Wine Staging 9.4.

**Comment by hyuri** [comment] 2024-03-25 19:23
I noticed this while trying to downgrade Wine Staging to 9.4 (note the "wine-stage-amd64 is not available"):
![image](https://github.com/robbert-vdh/yabridge/assets/18584014/730d4bfd-361e-4687-b867-2b92c28afa14)

And x86 plugins are working in Reaper.

**Comment by robbert-vdh** [comment] 2024-03-25 21:00
Wine 9.5 seems to have broken Winelibs, at least on 64-bit Wine. You'll need to [downgrade](https://github.com/robbert-vdh/yabridge?tab=readme-ov-file#downgrading-wine) to an earlier version of Wine for now. I'll do some digging and create a Wine bug report if there's not one already. Last time this has happened has been a while ago, but Winelib isn't a very widely used Wine version and it usually not tested, so these things happen from time to time.

**Comment by robbert-vdh** [comment] 2024-03-25 21:59
Another temporary solution would be to edit `yabridge-host.exe` and to change `wine` on line 33 to `wine64`. It's specifically the interaction between the WoW64 `wine` binary and 64-bit Winelibs that broke.

https://github.com/wine-mirror/wine/commit/85d029e3b01f6dd35a86cc07796af982d66e4a03 is the relevant Wine commit that caused this to break.

**Comment by cobe571** [comment] 2024-03-29 07:35
I found a similar issue with wine-staging 9.5 after the latest update. When I update Yabridge at the end I receive a message:

```
Warning: Could not run 'yabridge-host.exe' . Wine reported the following error:

       <no_output>
```

Reading the entire thread I decided to rollback Wine to 9.4 and now everything works really nicely. I'm actually on Debian 12 Stable with Xfce4. **To downgrade Wine to a previous version is pretty much simple on Debian**. Just remember that a full wine-staging install include these four packages:

- winehq-staging=9.4~bookworm-1 
- wine-staging=9.4~bookworm-1 
- wine-staging-amd64=9.4~bookworm-1 
- wine-staging-i386=9.4~bookworm-1

To downgrade the Wine Staging version, all the files necessary for the downgrade must be listed in the installation command like this in a single line:

`:~$ sudo apt install winehq-staging=9.4~bookworm-1 wine-staging=9.4~bookworm-1 wine-staging-amd64=9.4~bookworm-1 wine-staging-i386=9.4~bookworm-1`

Hope that helps. Thanks for Yabridge, I love it

**Comment by rolodoom** [comment] 2024-04-01 15:09
> @rolodoom: Just so you know, one of the current wine-staging patches [prevents some VST plugins from working](https://bugs.winehq.org/show_bug.cgi?id=56396), including Plogue sforzando and ARIA Engine. This was broken in wine-staging 9.3, but I'm not sure if it's been fixed yet in 9.4. Anyway, you may wish to downgrade to 9.2 if any of your plugins are affected. Wine-devel is not affected.

Thanks for the info. I finally installed winehq-stable v9.0 'cause some other software won't work with staging. As far as I checked, the plugins I used are working.

**Comment by 0CCULTIST** [comment] 2024-04-01 17:13
@robbert-vdh I'd recommend pinning this issue and making the current incompatible version displayed more prominently on the Github page. 

For Debian users, I recommend holding the packages back until a new WINE version is available. 
`sudo apt-mark hold wine-staging-amd64 wine-staging-i386 wine-staging winehq-staging`

`unhold` once it's safe to do so. Cheers!

**Comment by chevyvan10** [comment] 2024-04-08 04:05
Having with same issue with wine-staging 9.6. Had to revert back to 9.4.

**Comment by robbert-vdh** [comment] 2024-04-22 17:12
Yes, the MR that would fix it again has still not been merged. There doesn't seem to be a clear time frame on when that will happen because there's still some concerns that need to be addressed.

**Comment by giantg** [comment] 2024-04-30 16:48
I'm completely baffled by this, but I "accidentally" tried running a VST that has been crashing since this issue was reported after updating to the ArchLinux wine 9.7-1 package.  (Long story, but I had done a full `pacman -Syu` system update and forgot that I had to re-build wine 9.4-1 that I cloned from the ArchLinux official package repository).  

Well, I'm somewhat glad I did...  The problem plugin (Thimeo StereoTool) which was full on crashing Reaper on ArchLinux now loads against wine 9.7-1 at least for my specific use case on my specific machine.  However, I still have another laptop at home that the plugin still crashes on (it's on ArchLinux as well and on that machine I'm forced to re-compile wine 9.4-1).  Maybe it's the specific plugin that I'm using that is not so much dependent on the problem code, but I figured I would share my experience.  Hopefully this is helpful and not just a spam comment (let me know if it is and I'll delete it).

HUGE Thank you to the yabridge development team!  This project/code is AMAZING!  Letting us use windows VSTs/VSTi's on Linux!

**Comment by paulopinheiro** [comment] 2024-05-01 03:22
> > @rolodoom: Just so you know, one of the current wine-staging patches [prevents some VST plugins from working](https://bugs.winehq.org/show_bug.cgi?id=56396), including Plogue sforzando and ARIA Engine. This was broken in wine-staging 9.3, but I'm not sure if it's been fixed yet in 9.4. Anyway, you may wish to downgrade to 9.2 if any of your plugins are affected. Wine-devel is not affected.
> 
> Thanks for the info. I finally installed winehq-stable v9.0 'cause some other software won't work with staging. As far as I checked, the plugins I used are working.

Doesn't winehq-stable affect Yabridge?

**Comment by queengab** [comment] 2024-05-02 10:55
Hi,

thanks for this thread.
I have the same problem since wine was updated to 9.5.
I'm running an archlinux distro 6.7.0.6.realtime1-2-rt  with wine 9.7.1 and last yabridge.
The problem is not yet solved.
I'm not very a deep understanding of programming and compiling .

> Another temporary solution would be to edit yabridge-host.exe and to change wine on line 33 to wine64. It's specifically the interaction between the WoW64 wine binary and 64-bit Winelibs that broke.

How can i do it? Can i edit the single file from source and recompile only this?

Or i will wait for the MR.

Thanks!
Bye

**Comment by robbert-vdh** [comment] 2024-05-04 14:17
With the merge of https://gitlab.winehq.org/wine/wine/-/merge_requests/5400 this issue is now resolved again for Wine 9.8 onwards.

**Closed by robbert-vdh** 2024-05-04 14:17 UTC

**Comment by ManuLinares** [comment] 2024-05-04 16:14
Tested on wine 9.8, this is fixed now.

Thanks for the update

**Comment by QXR9** [comment] 2024-05-19 17:13
Wine 9.9 KDE Neon, still same issue. IDK it is only me or not.

**Comment by Jupek1** [comment] 2024-06-02 18:50
For me wine-staging 9.9 did not cause any noticeable problems but update to 9.10 did same plugin scanning problems as before (update from 9.4 -> 9.5) e.g. Reaper would not start etc. Thanks to Timeshift it was easy to revert back to 9.9. My OS is Linux Mint 21.3.

![Screenshot from 2024-06-02 21-33-33](https://github.com/robbert-vdh/yabridge/assets/94317851/5d741f61-a6e9-412e-ba06-fb7c6ab1ffb5)
![Screenshot from 2024-06-02 21-29-48](https://github.com/robbert-vdh/yabridge/assets/94317851/2367dfb1-2239-4728-a156-2a844974143f)
