### ISSUE TITLE
(Bug?) Sonarworks reference 4 plugin not discovered in Reaper

### ISSUE THREAD

**Issue by score100** [robbert-vdh/yabridge#162] opened 2022-02-11 14:17 UTC
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Background: Sonarworks used to develop their vst plugin also for linux for a while, but that is unfortunately no longer the case. Therefore I've tried to see if I can get their windows vst-version working. 

I can put the .dll plugin into my VST2 directory. Yabridge-sync finds it and does and creates a .so. But unlike other plugins in the folder Reaper just will not find it. Can not see why, even after re-scanning and re-launching the app several times.

Any help on this? I'm still new to this fabulous program but so far setting up vst's had been a breeze.

### What did you expect to happen?

That Reaper would discover the plugin

### What actually happened?

It's untraceable

### Operating system

Lubuntu 20.04

### How did you install yabridge?

From the release page

### yabridge version

3.7.0

### yabridgectl version

3.7.0

### Wine version

wine-7.1 (Staging)

### Plugin

Sonarworks Reference audio

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Reaper

### Debug log

No log shows up in /tmp/ :(

### Anything else?

It looks to me like it had actually recognized previously that there is indeed a plugin. But it doesn't show up in the list of plugins.

**Comment by robbert-vdh** [comment] 2022-02-11 14:25
Oh and Sonarworks Reference 4 does still have a Linux version, I think it's just hidden somewhere deep on a support page now. Or you may need to use the wayback machine to find it if they've taken down that page in the meantime.

**Comment by score100** [comment] 2022-02-11 15:15
Thanks for the swift reply!
> Can you show me a screenshot of the directory containing the VST2 plugin's .dll file and the .so file created by yabridgectl in a file manager/from `ls -Al`, a screenshot of the plugin locations dropdown in REAPER, and the plugin blacklist dropdown in REAPER?
![screen3](https://user-images.githubusercontent.com/10707729/153617549-e3842ea9-afba-4c0d-b17d-b9fe3e56257c.jpg)
![screen2](https://user-images.githubusercontent.com/10707729/153617554-bb67fcb1-5e4b-4f43-ba43-f270c18e9ba6.jpg)
![screen](https://user-images.githubusercontent.com/10707729/153617557-e7c739be-72b8-4fcd-af57-db7526768924.jpg)

Here you go
[](url)
> Oh and Sonarworks Reference 4 does still have a Linux version, I think it's just hidden somewhere deep on a support page now. Or you may need to use the wayback machine to find it if they've taken down that page in the meantime.

All I found so far where dead links. Might be able to retrieve it by contacting Sonarworks. Anywhow, they already said they've abandoned it and not getting any futures updates feels like a drawback when it comes to investing in a license.

**Comment by robbert-vdh** [comment] 2022-02-12 14:47
(Sorry I was away for a day!)

Likely the plugin relies on some library that's either not present or disabled in your Wine prefix. Since the plugin is blacklisted, REAPER won't try scanning it again. So you'll need to:

1. Close REAPER if you already have it running, then reopen it with `rm -f /tmp/yabridge.log; env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=1+editor reaper`. Make sure you **don't** load a project or anything else.
2. Go to that 'Plugins that failed to scan' dialog again, and click on Sonarworks Reference plugin at the bottom of that list.
3. You'll now have a log file at `/tmp/yabridge.log`. Reading through that you can probably already figure out what the problem is, but you can also attach it here. If for whatever reason that file does not get created, check REAPER's output in your terminal from the moment you tried to rescan the plugin.

**Comment by score100** [comment] 2022-02-15 17:54
Now worries about being away, you already deserve credit enough for all of this :)
Here is the log
[https://pastebin.com/Stv6f34V](url)

Did not found any clear instructions online how to deal with this.

**Comment by robbert-vdh** [comment] 2022-02-15 17:59
Did you launch REAPER with the command I told you to use and did you copy this from `/tmp/yabridge.log`? There's a lot of information missing from the output you posted.

**Comment by score100** [comment] 2022-02-15 18:02
Hi I did, but realized I might have closed one window to early.
Here is one again [https://pastebin.com/SH10hC9X](url)

**Comment by score100** [comment] 2022-02-15 18:27
No it isn't activated yet. But normally you shouldn't have a problem with that. From trying it on windows I know you will be able to load it just fine as a plugin and then are able to select a trial.

**Comment by score100** [comment] 2022-02-15 18:36
Also a thing to mention: as the sonarworks installer won't work on linux I just copied the .dll file from my windows vst folder to my linux wine -vst folder. Could it be that the .dll of a vst depends on other files set in the installation?

**Comment by robbert-vdh** [comment] 2022-02-15 19:51
Yeah that's definitely the problem. Software that doesn't come in a .zip archive is almost never portable like that.

**Comment by robbert-vdh** [comment] 2022-05-01 14:15
Closing this since this is a configuration issue and there has not been a response in a while.

**Closed by robbert-vdh** 2022-05-01 14:15 UTC
Labels: configuration-issue
