### ISSUE TITLE
plugins get duplicated or blacklisted in Mixbus 5 and 6

### ISSUE THREAD

**Issue by nr1971** [robbert-vdh/yabridge#11] opened 2020-05-09 04:27 UTC
Hi, so far this doesn't seem to working correctly for Mixbus 5/6 (also Ardour 6 rc1). If I make symlinks to my plugins they scan ok but I get a duplicate of the first plugin loaded. Using the copy method results in the plugins being blacklisted. I noticed something strange though. If I start Mixbus in the terminal *sometimes* it works- I clear the cache, rescan and bam the plugins show up and are working, although the couple times I did have working plugins it didn't last long and resulted in Mixbus crashing. I was using Ubuntu 18.04 and yabridge 1.0.0 and 1.1.0 and also just upgraded to Ubuntu 20.04 to see if anything changes but I am still seeing the same behavior. All the plugins I'm testing work in Carla as well as in Mixbus when loading them with Carla so I'm not sure if there is something going on in yabridge or Mixbus.

**Comment by nr1971** [comment] 2020-05-09 04:28
I should also add I'm using wine staging 5.6

**Comment by robbert-vdh** [comment] 2020-05-09 09:34
Symlinks will sadly only work with hosts that load each plugin in a new process (i.e. sandboxing), since otherwise you would essentially be loading the same file multiple times into the same process, which is not going to work. For the copying method you should make sure that the directory of `yabridge-host.exe` is somewhere in your `PATH` environment variable so the plugin can find the Wine host application. You can quickly check whether this is configured correctly by opening a terminal and running `which yabridge-host.exe`. After editing the environment variables in your profile you typically have to log out and back in again, but if you don't want to log out you could also temporarily launch your DAW from a terminal once `which yabridge-host.exe` correctly finds yabridge.

**Comment by nr1971** [comment] 2020-05-09 14:15
Hi, so I have set the path to yabridge in .bashrc and get the correct directory upon the output of the "export $PATH" command. 
"which yabridge-host.exe" returns: /home/neil/.local/share/yabridge/yabridge-host.exe
Attached is a copy of the terminal output from Mixbus6 when trying to add 3 plugins: DD Channel.so, TDR Nova.so and DigitsVST_x64.so. As I stated previously if I just run the .desktop launcher for Mixbus6 these plugins (or any that I've tried so far) get immediately blacklisted. However for some reason when running Mixbus6 from the terminal the scan completes and the plugins show up. This however seems to lead to a crash in Mixbus or Wine? Some plugins seem to timeout on the scan as well.

[mixbus6-terminal-output.txt](https://github.com/robbert-vdh/yabridge/files/4603617/mixbus6-terminal-output.txt)
[yabridge.log](https://github.com/robbert-vdh/yabridge/files/4603618/yabridge.log)
[backtrace.txt](https://github.com/robbert-vdh/yabridge/files/4603621/backtrace.txt)

**Comment by robbert-vdh** [comment] 2020-05-09 14:52
`~/.bashrc` is only supposed to be read for interactive shell sessions (i.e. when you open a terminal, and not when you launch applications from the GUI using a .desktop file) although by default some distros will read this file during startup anyways because it can get a bit confusing otherwise. The proper place to add `/home/neil/.local/share/yabridge` to your `PATH` would be in `~/.bash_profile`, or `~/.profile` if the former does not exist. I've just added a section on this a few hours ago because I know it can get a bit confusing!

And thanks for the logs! I think I'll have to poke around a bit in Mixbus6 myself because everything seems to be working fine until it asks the plugin to start processing audio. I'll get back to you when I know more.

**Comment by nr1971** [comment] 2020-05-09 15:28
Sounds good, thanks! Changing the path to ~/.profile allows the plugins to be picked up in the scan now instead of being blacklisted however *removing* any loaded plugin causes an instant crash.

**Comment by robbert-vdh** [comment] 2020-05-09 16:48
I've just downloaded Mixbus 6.0.702 to see if either we or Mixbus6 is doing something weird when closing plugins. After a bit of investigation I feel like it might be a bug in Mixbus6 rather than an issue on our side. My observations are:

- You can open a plugin, remove that plugin, open another instance of that same plugin, remove that instance etc. without any issues.
- If you can open a plugin and then open second, different plugin, then you can remove the first plugin without any issues, but removing the second plugin will cause Mixbus6 to crash. This happens for any combination of plugins, and removing the second plugin will crash Mixbus regardless of whether or not you remove the first plugin first.
- The interesting part is that yabridge itself does actually, as in it returns a `1` value when Mixbus calls `effClose()` on yabridge as you would expect so there are no crashes within yabridge.

At the moment I don't have any native Linux VST2 plugins to test with (Hive and Presswerk are both VST3), so I can't confirm if this also happens for regular native VST2 plugins.

**Comment by nr1971** [comment] 2020-05-09 17:36
Hi, using native VST2 plugins is no issue and doesn't result in any odd behavior or crashing. It is maybe worth noting that using Carla rack with windows vsts does work and does not result in a crash when removing the plugin(s) in any order of opening or closing them. Could there be something causing Mixbus to behave differently or is Carla doing something different than yabridge that prevents the crash?

**Comment by robbert-vdh** [comment] 2020-05-09 17:52
Which native VST2 plugins have you tried with Mixbus? I personally don't have any, so I couldn't test it myself. For instance Carla's CarlaRackFX and CarlaPatchbayFX plugins are both in VST3 format. Yabridge is completely transparent to the host, so it won't be able to differentiate between a Windows plugin running under yabridge or a regular native Linux VST2 plugin.

**Comment by nr1971** [comment] 2020-05-09 18:04
I have Maximal and the demo of Complexor 2 from Venomode- found here:
[https://venomode.com/plugins](url)
A couple more are TAL-Chorus-LX and TAL-Reverb-4 which are free from here:
[https://tal-software.com/products](url)

**Comment by robbert-vdh** [comment] 2020-05-09 18:24
Oh I didn't now that TAL plugins are available for Linux now, that's awesome! And since the problem does indeed not occur with those plugins, then there is definitely something weird going on. I just tested this with Ardour 5 (Mixbus6 is based on Ardour 6 as far as I'm aware), and the exact same issue happens there. The odd thing is that it doesn't happen with other VST hosts, and that it only happens in Ardour/Mixbus on the second plugin. Since the actual plugin closing procedure works fine, my guess is that something breaks when host tries to unload the second plugin's `.so` file from its process. I'll investigate some more soon!

**Comment by robbert-vdh** [comment] 2020-05-09 19:38
I could only think of a single thing that could cause this, and it appears my hunch was right! At least on my machine the issue is fixed by 54295f3a27a85bfc28aa4fb2d2cff85e0e600013. If you would like to give it a shot, you can grab a build at:

https://github.com/robbert-vdh/yabridge/actions/runs/100147666

**Comment by nr1971** [comment] 2020-05-09 20:01
Ok so I've just tried that build and now there is no crashing when removing plugins (awesome!) but I'm getting some plugins blacklisted now that were working previously! These in particular-
http://www.vst4free.com/free_vst.php?plugin=FerricTDS&id=660
https://myvst.com/vst-instruments/vst-effects/density-mkiii-freeware/
http://www.vst4free.com/free_vst.php?plugin=Rescue_MK2&id=663
Could you test and see if these are working for you?

**Closed** 2020-05-09 20:32 UTC
Labels: bug

**Comment by robbert-vdh** [comment] 2020-05-09 20:46
These VoS plugins are a blast from the past, haven't seen them in ages haha. The problem with FerricTDS is that the zip archive on vst4free.com is malformed. It contains a named `FerricTDS_1.5.1\FerricTDS.dll`, which should of course be a directory containing a plugin called `FerricTDS.dll`. Wine can get a bit picky about file paths, and it sure doesn't like this one. If you rename the plugin to `FerricTDS.dll` then Wine/yabridge is able to load it.

Aside from that small issue these plugins seem to work great for me! Nice to see that they still work great. The only issue I've found is that they don't work in Carla, but that's an issue with Carla itself because it tries to set the plugin's preset even though the plugin just explicitely told Carla that it does not support that.
