### ISSUE TITLE
REAPER crashes after loading plugins (OpenSUSE TW)

### ISSUE THREAD

**Issue by brainsweetiesss** [robbert-vdh/yabridge#285] opened 2023-11-27 00:24 UTC
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

Hi there!

First off thanks for the great work you're doing with this project. Much appreciate it.

Regarding my issue: I'm trying to load 2 plugins from my default ~/.wine prefix and both of them make REAPER crash when I select/open them. I did some research and found some old threads recommending to install a few winetricks on the prefix but that didn't work. The winetricks I installed were vcrun2019 and gdiplus. According to the logs the issue is related to memory locking but the recommended package to install to solve this issue is not available on OpenSUSE TW (AFAIK) . That package is realtime-privileges btw.

Since the package is unavailable I tried to see if there was another way to fix this issue and found a guide that said to change the default values found under /etc/security/limits.d/99-audio.conf

I updated the default values to:
@audio - rtprio 99
@audio - memlock 4000000
@audio - nice -20

But that also didn't have any effect

### What did you expect to happen?

For the plugins to load properly

### What actually happened?

The application crashes

### Operating system

OpenSUSE Tumbleweed

### How did you install yabridge?

SUSE repos

### yabridge version

5.0.5

### yabridgectl version

5.0.5

### Wine version

wine-8.20 (Staging)

### Plugin

TSE BOD / Ampeg VST Classic

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

REAPER

### Desktop environment or WM

KDE Plasma X11

### GPU model

AMD 5700XT

### GPU drivers and kernel

Mesa 23.2.1 / Kernel 6.6.2-1-default

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/13468519/yabridge.log)

**Comment by OzFalcon** [comment] 2023-12-19 23:01
I found this problem also when using Wine 8. The plugins crashed and that froze or crashed Reaper.
Moving to Wine 9-RC2 (devel branch as of this post) resolved the Reaper (and plugin) crashes for me.
Go to wine-hq and get the devel branch. There appears to be binaries for SUSE (Leap and Tumbleweed).

**Comment by Desidiosus** [comment] 2023-12-20 21:04
I may be wrong but this issue might be caused by the multimedia:proaudio repo building yabridge against an old wine version. The wine version available in that repo is still 7.20.

I remember encountering something similar and I replaced yabridge from the repos with the one available here in the releases, which fixed crashing for me.

**Comment by robbert-vdh** [comment] 2023-12-30 13:25
@brainsweetiesss Have you tried @Desidiosus's suggestion and replaced the yabridge version from your repos with the binaries from the releases section? You'll need to to remove the package first, and then follow the instructions from the readme.

**Comment by dikey0ficial** [comment] 2023-12-30 17:11
Fixed downgrading wine to 7.x branch

**Comment by robbert-vdh** [comment] 2023-12-30 17:22
Since it seems to be a packaging issue with these OpenSUSE repos, I'm closing this issue for now.

**Closed by robbert-vdh** 2023-12-30 17:22 UTC
