### ISSUE TITLE
REAPER hangs on exit

### ISSUE THREAD

**Issue by gaydenko** [robbert-vdh/yabridge#234] opened 2023-01-27 20:59 UTC
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

It seem on exit REAPER waits for some signal from plugin host, but doesn't receive it. It results on exit hand. To help REAPER to exit I can start `wineserver -k` from terminal. Both 5.0.2+7.20 and 5.0.3+7.22 was tried with the same result. 

### What did you expect to happen?

REAPER exit.

### What actually happened?

REAPER hangs. After `winserver -k` started on another terminal REAPER exits.

### Operating system

Manajro

### How did you install yabridge?

AUR or pacman

### yabridge version

5.0.2 and 5.0.3

### yabridgectl version

5.0.2 and 5.0.3

### Wine version

7.20 and 7.22

### Plugin

Any (Temp Delay, Emergence1,...

### Plugin type

VST3

### Plugin architecture

64-bit

### Host

REAPER 6.73

### Desktop environment or WM

KDE Plasma

### GPU model

amdgpu

**Comment by robbert-vdh** [comment] 2023-01-30 15:10
If it happens with any plugin it's very unlikely to be related to yabridge. Someone in the yabridge Discord was having issues with REAPER and PipeWire. I'd check REAPER's log messages when you try to close it.

**Comment by gaydenko** [comment] 2023-01-30 15:15
@robbert-vdh 
Sorry, I don't understand. yabridge is the only app using wine. On `wineserver -k` REAPER does exit. There are no any relation with pipewire, as far as audio interface is turned off via pavucontrol (pipewire doesn't see it).

And well, I have tried projects without yabridge supplied plugins, and there isn't any problem with REAPER exit.

**Comment by robbert-vdh** [comment] 2023-01-30 15:18
Well you're the only person having this issue. So it's something to do with your setup. Like I said, you'll need to look at the logs for clues.

**Comment by gaydenko** [comment] 2023-01-30 15:26
[reaper-yabridge.log](https://github.com/robbert-vdh/yabridge/files/10537144/reaper-yabridge.log)

This is a complete sessiion log: start REAPER, play few seconds something, stop, hit exit. At this moment jack client is closed, but REAPER does wait for something. Then `wineserver -k` - REAPER is closing successfully.

**Comment by a-parhom** [comment] 2023-01-30 17:06
Looks like I'm having the same problem. With some projects using yabridge Reaper hangs on exit. There is a workaround though: if I first close the project from the menu and then exit Reaper it doesn't hang.

**Comment by vssasks** [comment] 2023-02-01 19:26
I dont have such problems

**Comment by gaydenko** [comment] 2023-02-01 19:40
> I dont have such problems

How can this information be used?

**Comment by vssasks** [comment] 2023-02-01 21:26
Use other plugins. Better old ones like hyperprism... older ones are less problematic

**Comment by dikey0ficial** [comment] 2023-02-06 19:03
maybe this is related:
Reaper hangs on scanning vst plugins (stops on LABS, 64bit). openSUSE Tumbleweed, wine-staging 8.1, yabridgectl version 5.0.3 installed from geekos repo (multimedia:proaudio)

**Comment by robbert-vdh** [comment] 2023-02-06 19:48
> Looks like I'm having the same problem. With some projects using yabridge Reaper hangs on exit. There is a workaround though: if I first close the project from the menu and then exit Reaper it doesn't hang.

Do you have any more information? Like I said, I can't reproduce this. And I haven't heard anyone on the Discord have this problem either.

**Comment by gaydenko** [comment] 2023-02-06 20:14
@robbert-vdh  What could we supply more except for a log as I have already done?

**Comment by robbert-vdh** [comment] 2023-02-06 20:50
> @robbert-vdh What could we supply more except for a log as I have already done?

I have no idea. Like, if you open REAPER, insert Valhalla SuperMassive on a track, and then immediately close REAPER, does it hang for you? And try creating a log with the `YABRIDGE_DEBUG_LEVEL=1+editor` environment variable set.

**Comment by gaydenko** [comment] 2023-02-06 21:19
> `YABRIDGE_DEBUG_LEVEL=1+editor`

This is with Tempo Delay -  winserver killing was needed.

[tempo-delay-only.tar.gz](https://github.com/robbert-vdh/yabridge/files/10669212/tempo-delay-only.tar.gz)

It is interesting, I have also tried absolutely tiny project with a couple of Emergence1 (via yabridge) plugin instances (prepended by F-em), and at this case REAPER does exit during 8-9 seconds. 

[emergence1-ok.tar.gz](https://github.com/robbert-vdh/yabridge/files/10669241/emergence1-ok.tar.gz)

P.S. This time yabridge 5.0.3, wine-staging is 8.0 (reaper is still 6.73).

**Comment by a-parhom** [comment] 2023-02-06 22:28
I can confirm, that on relatively small (or maybe without some specific plugins?) projects Reaper exits properly. I'll try to get some logs tomorrow.

**Comment by robbert-vdh** [comment] 2023-02-21 14:25
I got an email telling me about a similar issue involving plugin groups, stating that plugins in plugin groups with more than one active plugin instance would hang when removing the instance. I ended up tracking that down to a regression in yabridge 4.0.0 and I fixed it in ee971f610e557321b8b963f4a461026eb1bcaea6 (C++'s move semantics are real footguns ha). It didn't occur to me that all of the cases of hanging plugins from this issue are using plugin groups with multiple instances. So this should be fixed now on the latest master branch version of yabridge. Could you give that a try? There are instructions for installing a development build here:

https://github.com/robbert-vdh/yabridge#installing-a-development-build

**Comment by gaydenko** [comment] 2023-02-21 17:52
@robbert-vdh 
Have tried yabridge-git on Manjaro - the problem has gone, great.

**Comment by robbert-vdh** [comment] 2023-02-23 14:40
This should now be fixed as of yabridge 5.0.4's release.

**Closed by robbert-vdh** 2023-02-23 14:41 UTC
Labels: bug

**Comment by vssasks** [comment] 2023-03-11 13:43
What's wrong with your bridge? 2times more cpu consumption than with linvst...

**Comment by robbert-vdh** [comment] 2023-03-11 13:51
> What's wrong with your bridge? 2times more cpu consumption than with linvst...

Can you explain what you mean by that? I saw you post that four times yesterday on the LinVst and LinVst-X repos. How are you obtaining those numbers? Do you have a plugin editor open or not? Yabridge runs editors at higher frame rates by default so interacting with GUIs is smoother. And also, CPU usage is not important at all for realtime audio unless you're using a single or dual core CPU. DSP load is the important metric.

**Comment by vssasks** [comment] 2023-03-11 14:03
In reaper you can see cpu consumption at lowest part of opened fx window. Perhaps you can take his mac os code and adapt for your capabilities such as different prefixes support and better gui support. As he told abique and airwave codes are worse for rt and more hungry
