### ISSUE TITLE
Yabridged plugins do not accept any mouse or keyboard input.

### ISSUE THREAD

**Issue by Shorkerrr** [robbert-vdh/yabridge#389] opened 2024-12-22 21:23 UTC
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

As title says, i cant manipulate any parameter within any of my currently yabridged plugins. 
Has worked before with mouse, however never with keyboard input

### What did you expect to happen?

Knobs and other parameters to be moved around, values change. 

### What actually happened?

When interacting with window with mouse or keyboard nothing happens. 

When interacting with DAWs own parameters then the expected parameters get changed in function and in UI.

### Operating system

Arch Linux

### How did you install yabridge?

AUR Package

### yabridge version

5.1.1

### yabridgectl version

5.1.1

### Wine version

wine-9.22

### Plugin

All using yabridge

### Plugin type

both VST2 and VST3

### Plugin architecture

64-bit

### Host

Bitwig Studio 5.27

### Desktop environment or WM

Hyprland

### GPU model

NVIDIA RTX 3060 12 GB

### GPU drivers and kernel

Proprietary 565.77

### Debug log

[2024-12-22 22:15:18.336 info] About to start the following process:  /opt/bitwig-studio/bin/show-splash-gtk /opt/bitwig-studio/resources/splash-bitwig-studio.png
[2024-12-22 22:15:18.336 info] Child process launched with PID 37823
[2024-12-22 22:15:18.336 info] Backing up log file "/home/Melker/.BitwigStudio/log/BitwigStudio.log" to "/home/Melker/.BitwigStudio/log/BitwigStudio-previous-run.log"
[2024-12-22 22:15:18.337 info] About to start the following process:  /opt/bitwig-studio/bin/BitwigStudio -cp /opt/bitwig-studio/bin/bitwig.jar:/opt/bitwig-studio/lib/cp:/opt/bitwig-studio/bin/libs.jar -Dorg.sqlite.lib.path=/opt/bitwig-studio/lib/bitwig-studio -XX:+UseZGC -XX:+ZGenerational -Xms300m -Xmx3g -Djava.io.tmpdir=/tmp/bitwig-Melker -DinstallationRoot=/opt/bitwig-studio -DsplashPid=37823 -Djava.awt.headless=true -XX:ErrorFile=/home/Melker/.BitwigStudio/bitwig-studio-jvm-crash.log com.bitwig.flt.app.BitwigStudioMain
[2024-12-22 22:15:18.337 info] Redirecting stdout to /home/Melker/.BitwigStudio/log/BitwigStudio.log
[2024-12-22 22:15:18.337 info] Redirecting stderr to /home/Melker/.BitwigStudio/log/BitwigStudio.log
[2024-12-22 22:15:18.337 info] Child process launched with PID 37824

Bitwig Studio 5.27 starts correctly. No issues, i load Izotope Trash 2 as VST3 Example. Input issue is experienced

### Anything else?

Keyboard input has never worked, example: authorizing Nimble Kick (VST3) was not possible due to me not being able to type in the authkey. Otherwise unnoteworthy.

(UNRELATED) Certain graphical glitches and etc, however i think there are fixes for most of these in the known issues & troubleshooting through adding certain dlls through winetricks.

**Comment by siborg** [comment] 2024-12-22 21:27
Please downgrade to 9.21 - there are issues with wine 9.22.

Cheers,

Simon

**Comment by Shorkerrr** [comment] 2024-12-22 21:37
thanks that fixed my mouse, but as stated above keyboard is not working still

**Comment by 0CCULTIST** [comment] 2024-12-23 16:07
Some plugins require your mouse to literally be "inside" the text box & at bare minimum the window. Wine currently has issues with layering & focusing of submenus/popups. I believe this can also be impacted by your compositor/WM.

**Comment by ManuLinares** [comment] 2024-12-27 00:18
> @siborg Please downgrade to 9.21 - there are issues with wine 9.22.


Is there a bug report on the wine side of things we can link to?

**Comment by ManuLinares** [comment] 2024-12-27 15:04
duplicate of https://github.com/robbert-vdh/yabridge/issues/382

**Comment by robbert-vdh** [comment] 2024-12-27 15:08
This is indeed a duplicate of #382, closing to keep the discussion in one place!

**Closed by robbert-vdh** 2024-12-27 15:08 UTC
