### ISSUE TITLE
Segmentation fault exiting Reaper

### ISSUE THREAD

**Issue by David-Else** [robbert-vdh/yabridge#238] opened 2023-03-03 12:28 UTC
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

I run any bridged plugins when I close Reaper it exits with a Segmentation fault . The plugins are working, but something must be wrong. If I run Reaper from the terminal when I close I get something like:

```
19:43:18 [fbvc-8Fdghjkr] [Wine STDERR] 0024:fixme:dwrite:dwritefontface5_HasVariations 000000000103FB30: stub
^[[5;2~19:44:46 [fbvc-8Fdghjkr] [Wine STDERR] 0024:fixme:font:NtGdiRemoveFontMemResourceEx (0xf9ade171) stub
19:44:46 [fbvc-8Fdghjkr] [Wine STDERR] 0024:fixme:x11drv:X11DRV_DestroyNotify window 0x1007e/5e00003 destroyed from the outside
19:44:46 [Elephant-2OPVXcoy] [Wine STDERR] 011c:fixme:x11drv:X11DRV_DestroyNotify window 0x1006a/5800003 destroyed from the outside
Segmentation fault (core dumped)
```
BUT the plugin that is listed at the end could be Voxengo Elephant or TDR SlickEQ, I don't think it is a problem with any particular bridged plugin. There is no segmentation fault unless I am using yabridge.

I happens with bridged clap plugins too, here is a full bucket clap synth:

```
12:41:32 [fb330064-1ENWhmtv] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
12:41:33 [fb330064-1ENWhmtv] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
12:41:33 [fb330064-1ENWhmtv] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
12:41:33 [fb330064-1ENWhmtv] [Wine STDERR] 0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
12:41:33 [fb330064-1ENWhmtv] [Wine STDERR] Initializing yabridge host version 5.0.4
12:41:33 [fb330064-1ENWhmtv] [Wine STDERR] Preparing to load CLAP plugin at '/home/david/.wine/drive_c/Program Files/Common Files/CLAP/fb330064.clap'
12:41:33 [fb330064-1ENWhmtv] [Wine STDERR] Finished initializing '/home/david/.wine/drive_c/Program Files/Common Files/CLAP/fb330064.clap'
12:41:33 [fb330064-1ENWhmtv] [Wine STDERR] 0024:fixme:imm:ImeSetActiveContext (0000000000010056, 1): stub
12:41:33 [fb330064-1ENWhmtv] [Wine STDERR] 0024:fixme:imm:ImmReleaseContext (0000000000020046, 0000000000010056): stub
12:41:34 [fb330064-1ENWhmtv] [Wine STDERR] 0024:fixme:dwrite:dwritefontface5_HasVariations 000000000103FB40: stub
12:41:34 [fb330064-1ENWhmtv] [Wine STDERR] 0074:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
12:41:34 [fb330064-1ENWhmtv] [Wine STDERR] 0074:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
12:41:40 [fb330064-1ENWhmtv] [Wine STDERR] 0024:fixme:font:NtGdiRemoveFontMemResourceEx (0xf97c4241) stub
12:41:40 [fb330064-1ENWhmtv] [Wine STDERR] 0024:fixme:x11drv:X11DRV_DestroyNotify window 0x20046/4e00003 destroyed from the outside
Segmentation fault (core dumped)
```

### What did you expect to happen?

No segmentation fault.

### What actually happened?

I got a segmentation fault.

### Operating system

RHEL 9 clone AlmaLinux 9.1

### How did you install yabridge?

directly from release page

### yabridge version

5.0.4

### yabridgectl version

5.0.4

### Wine version

8.0 (from official epel9 repo)

### Plugin

Voxengo Elephant, TDR SlickEQ... maybe more, see comments

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Reaper v6.75 Linux version

### Desktop environment or WM

Gnome 40

### GPU model

AMD

### GPU drivers and kernel

Messa 22.1.5 on Kernel 5.14.0

### Debug log

[yabridge.log](https://github.com/robbert-vdh/yabridge/files/10881614/yabridge.log)

### Anything else?

I am choosing ALSA in Reaper, I think it uses Pipewire.
```
Installed Packages
Name         : pipewire
Version      : 0.3.47
Release      : 2.el9_0
Architecture : x86_64
Size         : 74 k
Source       : pipewire-0.3.47-2.el9_0.src.rpm
Repository   : @System
From repo    : AppStream
Summary      : Media Sharing Server
URL          : https://pipewire.org/
License      : MIT
Description  : PipeWire is a multimedia server for Linux and other Unix like operating
             : systems.
```

**Comment by robbert-vdh** [comment] 2023-03-11 14:02
Sorry for the late response (here and on other issues, if anyone's reading this). I've been very busy in the last couple weeks.

There's nothing that would indicate the issue is directly related to yabridge, nor have I heard about this from other people, so figuring out what's happening may be difficult. I'd try these things in order:

- First of all, your system setup is not correctly set up for realtime audio. Since you're using PipeWire that means you're now using rtkit, which means that some things may randomly start crashing when they take too long. You'll want to fix this first. There are instructions for setting up realtime priviliges in the readme. Once you've fixed that the `realtime` field in the initialization message should say 'yes' (with no further warnings), and 'memlock limit' should say 'unlimited'.
- This is unrelated, but you shouldn't use the pipewire-alsa backend with REAPER. Pipewire-alsa is made so legacy ALSA-only applications can work with PipeWire, but REAPER also supports JACK. So you should just pipewire-jack instead. Pipewire-alsa needs to add another period of buffering/latency.
- If you still get crashes after fixing your realtime priviliges, then try the following. Create a new REAPER project, and insert a single plugin instance (like that `fb330064`) plugin. Save the project, then close REAPER. Now reopen REAPER with `gdb reaper`. Where `reaper` is how you'd normally launch REAPER from the terminal (so a full path to the `reaper` binary if it's not in your search `PATH`). Type `continue` in the prompt. When REAPER opens, load the project, and immediately close it again. Do you get a segfault? If so, try running `backtrace` and copy the output here. There won't be a lot of useful information there since both REAPER and yabridge are stripped release builds, but it could be starting point.
- Also, try loading yabridge in another host. If you have Carla installed, try running `carla-single vst2 ~/.vst/yabridge/path/to/plugin.so`, where `~/.vst/yabridge/path/to/plugin.so` is a path to a bridged yabridge plugin .so file.

**Comment by robbert-vdh** [comment] 2023-03-20 12:39
Awesome! Yes the `X11DRV_DestroyNotify window 0xXXXX destroyed from the outside` message is normal.

**Closed by robbert-vdh** 2023-03-20 12:39 UTC
